# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Match certificates and provisioning profiles for App Store"
  lane :match_appstore do
    match(type: "appstore", readonly: true)
  end

  desc "Match certificates and provisioning profiles for development"
  lane :match_development do
    match(type: "development", readonly: true)
  end

  desc "Build debug version"
  lane :build_debug do
    build_app(
      workspace: "CbMmobileapp.xcworkspace",
      scheme: "CbMmobileapp",
      configuration: "Debug",
      export_method: "development"
    )
  end

  desc "Build and upload to TestFlight"
  lane :deploy_testflight do
    match(type: "appstore", readonly: true)
    
    build_app(
      workspace: "CbMmobileapp.xcworkspace",
      scheme: "CbMmobileapp",
      configuration: "Release",
      export_method: "app-store"
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build and upload to App Store"
  lane :deploy_appstore do
    match(type: "appstore", readonly: true)
    
    build_app(
      workspace: "CbMmobileapp.xcworkspace",
      scheme: "CbMmobileapp",
      configuration: "Release",
      export_method: "app-store"
    )
    
    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true
    )
  end
end
